ZSH_THEME="nequissimus"
ZSH_CUSTOM="/home/nequi/dev/nequi-zsh"

CASE_SENSITIVE="false"
ENABLE_CORRECTION="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(docker git github gitignore kubectl sbt scala)

export TERMINAL="xterm"
export PATH="/home/nequi/bin:${PATH}"
export JAVA_HOME="${$(readlink -e $(type -p java))%*/bin/java}"

[[ -e ${ZSH}/oh-my-zsh.sh ]] && source ${ZSH}/oh-my-zsh.sh

alias mvn='mvn -q'
alias nano='nano -E -w -c'
alias volume='awk -F"[][]" "/dB/ { print $2 }" <(amixer sget Master)'
alias volume_up='amixer -q sset Master 5%+; volume'
alias volume_down='amixer -q sset Master 5%-; volume'
alias sbt='sbt -mem 4096'
alias docker_clean='docker kill $(docker ps -q); docker rm $(docker ps -a -q)'
alias docker_clean_dangling='docker images -qf dangling=true | xargs -r docker rmi'
alias docker_clean_images='docker kill $(docker ps -q); docker rm $(docker ps -a -q); docker rmi -f $(docker images -q)'
alias rsync='rsync -azvvP'
alias scrot='scrot -s'
alias fix_touchpad='sudo modprobe -r elan_i2c && sleep 5 && sudo modprobe elan_i2c' # ASUS UX305C
alias nix-repair-store='nix-store --verify --check-contents --repair'
alias weather='curl -k https://wttr.in | head -n -2'

alias docker_zk='docker kill zookeeper; docker rm zookeeper; docker run -d -p 2181:2181 --name zookeeper zookeeper:3.4.10'
function docker_kafka() { docker kill kafka; docker rm kafka; docker run -h $(hostname) --rm -it -p 9092:9092 --name kafka --link zookeeper:zookeeper -e KAFKA_ZOOKEEPER_CONNECT="zookeeper:2181" -e KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$(hostname):9092" -e KAFKA_CREATE_TOPICS="topic1:1:1,topic2:1:1" wurstmeister/kafka:0.10.2.1 }
function kafka_consume() { docker run -it --link kafka:kafka --entrypoint /bin/sh wurstmeister/kafka:0.10.2.1 -c "/opt/kafka_*/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic $1" }
function kafka_produce() { docker run -it --link kafka:kafka --entrypoint /bin/sh wurstmeister/kafka:0.10.2.1 -c "/opt/kafka_*/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic $1" }


setxkbmap -option ctrl:nocaps

function nix-search() { echo "Searching..."; nix-env -qaP --description '*' | grep -i "$1"; }
function nix-update() { echo "Updating user environment... "; nix-channel --update; nix-env -u '*'; nix-env -i $(nix-env -q | grep -v 'emacs'); }

function kube_alpine() { kubectl run --namespace=${1:-default} -i --tty alpine --image=alpine -- sh }
