export ZSH="${HOME}/.nix-profile/share/oh-my-zsh"

ZSH_THEME="nequissimus"
ZSH_CUSTOM="${HOME}/dev/nequi-zsh"

CASE_SENSITIVE="false"
ENABLE_CORRECTION="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(docker git github gitignore kubectl sbt scala)

export TERMINAL="urxvt"
export PATH="/home/nequi/bin:${PATH}"
export JAVA_HOME="${$(readlink -e $(type -p java))%*/bin/java}"

source ${ZSH}/oh-my-zsh.sh

alias mvn='mvn -q'
alias nano='nano -E -w -c'
alias volume='awk -F"[][]" "/dB/ { print $2 }" <(amixer sget Master)'
alias volume_up='amixer -q sset Master 5%+; volume'
alias volume_down='amixer -q sset Master 5%-; volume'
alias sbt='sbt -mem 4096'
alias docker_clean='docker kill $(docker ps -q); docker rm $(docker ps -a -q)'
alias docker_clean_dangling='docker images -qf dangling=true | xargs -r docker rmi'
alias docker_clean_images='docker kill $(docker ps -q); docker rm $(docker ps -a -q); docker rmi -f $(docker images -q)'
alias rsync='rsync -azvvP'
alias scrot='scrot -s'
alias fix_touchpad='sudo modprobe -r elan_i2c && sleep 5 && sudo modprobe elan_i2c' # ASUS UX305C
alias nix-repair-store='nix-store --verify --check-contents --repair'
alias weather='curl -k https://wttr.in | head -n -2'

setxkbmap -option ctrl:nocaps

function nix-search() { echo "Searching..."; nix-env -qaP --description '*' | grep -i "$1"; }
function nix-update() { echo "Updating user environment... "; nix-channel --update; nix-env -u '*'; nix-env -i $(nix-env -q | grep -v 'emacs'); }

alias kube_busybox='kubectl run -i --tty busybox --image=busybox -- sh'
