# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/653738c1-1c86-4349-9b09-6eb4b4b2ed32";
      fsType = "btrfs";
      options = ["noatime" "autodefrag" "discard" "ssd" "compress=lzo" "space_cache" "subvol=nixos"];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/653738c1-1c86-4349-9b09-6eb4b4b2ed32";
      fsType = "btrfs";
      options = ["noatime" "autodefrag" "discard" "ssd" "compress=lzo" "space_cache" "subvol=tmp"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/653738c1-1c86-4349-9b09-6eb4b4b2ed32";
      fsType = "btrfs";
      options = ["noatime" "autodefrag" "discard" "ssd" "compress=lzo" "space_cache" "subvol=home"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/266b9d55-1203-4332-b3b8-7accca80f028"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
