# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ac3a46cb-6d67-4383-945c-94ca010700d9";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/var/docker" =
    { device = "/dev/disk/by-uuid/ac3a46cb-6d67-4383-945c-94ca010700d9";
      fsType = "btrfs";
      options = [ "subvol=docker" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/ac3a46cb-6d67-4383-945c-94ca010700d9";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ac3a46cb-6d67-4383-945c-94ca010700d9";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8cfe49e0-8bf9-4307-9b5c-1512124a746d"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
