# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/15c7d240-8fc6-45db-91ef-8b72f68a5f49";
      fsType = "btrfs";
      options = "subvol=nixos";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1016-0561";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5b04396d-11d8-44ce-b4af-456320736a23"; }
    ];

  nix.maxJobs = 4;
}
