# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/579cab11-afd3-4ae6-a4e0-0cce3ac863ba";
      fsType = "btrfs";
      options = [ "noatime" "compress=lzo" "ssd" "discard" "space_cache" "commit=120" "subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2756-7EDA";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/579cab11-afd3-4ae6-a4e0-0cce3ac863ba";
      fsType = "btrfs";
      options = [ "noatime" "compress=lzo" "ssd" "discard" "space_cache" "commit=120" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/579cab11-afd3-4ae6-a4e0-0cce3ac863ba";
      fsType = "btrfs";
      options = [ "noatime" "compress=lzo" "ssd" "discard" "space_cache" "commit=120" "subvol=nix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/579cab11-afd3-4ae6-a4e0-0cce3ac863ba";
      fsType = "btrfs";
      options = [ "noatime" "compress=lzo" "ssd" "discard" "space_cache" "commit=120" "subvol=tmp" ];
    };

  fileSystems."/var/docker" =
    { device = "/dev/disk/by-uuid/579cab11-afd3-4ae6-a4e0-0cce3ac863ba";
      fsType = "btrfs";
      options = [ "noatime" "compress=lzo" "ssd" "discard" "space_cache" "commit=120" "subvol=var/docker/docker" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
