export ZSH="${HOME}/.nix-profile/share/oh-my-zsh"

ZSH_THEME="avit"
CASE_SENSITIVE="false"
ENABLE_CORRECTION="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(git)

export TERMINAL="xterm"
export PATH="/home/tsteinbach/bin:/var/setuid-wrappers:/home/tsteinbach/.nix-profile/bin:/home/tsteinbach/.nix-profile/sbin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/run/current-system/sw/bin:/run/current-system/sw/sbin:/home/tsteinbach/bin:/home/tsteinbach/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export JAVA_HOME="${$(readlink -e $(type -p java))%*/bin/java}"

source ${ZSH}/oh-my-zsh.sh

alias mvn='mvn -q'
alias nano='nano -E -w -c'
alias volume='awk -F"[][]" "/dB/ { print $2 }" <(amixer sget Master)'
alias volume_up='amixer -q sset Master 5%+; volume'
alias volume_down='amixer -q sset Master 5%-; volume'
alias javarepl='java -jar /home/tsteinbach/bin/javarepl.jar'
alias sbt='sbt -mem 4096'
alias docker_clean='docker kill $(docker ps -q); docker rm $(docker ps -a -q); docker rmi -f $(docker images -q)'
alias rsync='rsync -azvvP'
alias irssi='irssi --config=/etc/irssi/config'
alias pdf='evince'

alias fix_touchpad='sudo modprobe -r elan_i2c && sleep 5 && sudo modprobe elan_i2c' # ASUS UX305C
alias nix-repair-store='nix-store --verify --check-contents --repair'
alias fix_screens='xrandr --output DP2-3 --crtc 1 --auto --pos 0x0 --output DP2-2 --crtc 2 --primary --auto --pos 1920x0 --output eDP1 --auto --pos 3840x0'

#setxkbmap -option ctrl:nocaps
#[[ -z "${HOME}" ]] || [[ -e "${HOME}/Downloads" ]] && rm -rf "${HOME}/Downloads" && mkdir "${HOME}/Downloads"

function nix-search() { echo "Searching..."; nix-env -qaP --description '*' | grep -i "$1"; }
function nix-update() { echo "Updating user environment... "; nix-channel --update; nix-env -i $(nix-env -q | grep -v 'user-misc'); }

xsetroot -solid black
xsetroot -cursor_name left_ptr
